name = "ebike-pos-api"
main = "index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "ebike-pos"
database_id = "99f7271ade95d35b4ec0c1177248124f"

[vars]
# Domain Pages của bạn, hoặc "*" khi dev
ALLOWED_ORIGIN = "*"
