name = "ebike-pos-api"
main = "index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "ebike-pos"
database_id = "c3f7f057-ffa1-4d11-a1b2-3120c6b80ae2"

[vars]
# Domain Pages của bạn, hoặc "*" khi dev
ALLOWED_ORIGIN = "*"

[assets]
directory = "./dist"
binding = "ASSETS"
